### ISSUE TITLE
Agenda Topic

### ISSUE THREAD

**Issue by gastaldi** [jbott-bot/jbott#2]
When defining the initial agenda, we usually do:
# topic Agenda
# info Topic 1
# info Topic 2

So the meeting minutes display the agenda before proceeding to the topics.

Maybe jbott could generate the agenda based on #addtopic commands?

**Comment by maxandersen** [comment]
Not following. That is what it does. You can use #listtopics to state the remaining  agenda.

**Comment by gastaldi** [comment]
I'm talking about the generated minutes. The topics won't appear inside a #topic Agenda. Will #listtopics appear in the minutes?

**Comment by maxandersen** [comment]
So what you want is that besides the topics being listed normally in minutes (as listed on http://transcripts.jboss.org/meeting/irc.freenode.org/forge/2014/forge.2014-03-08-13.14.html) and #nextopic is only visible in http://transcripts.jboss.org/meeting/irc.freenode.org/forge/2014/forge.2014-03-08-13.14.log.html you want the #addtopic to show up when they are being made ?

Is it enough to have argument to #listtopics, i.e. #listtopics record and it will list the topics with #info or #idea tags ?

**Comment by gastaldi** [comment]
Yeah, I think that would be a good idea. Or the agenda could be generated automatically, since the topics are already known during the meeting.

**Comment by maxandersen** [comment]
I don't grok when you say "agenda could be generated automatically" since there is no indication that just because the first topic is named agenda it should list the agenda items in there.

The agenda is generated automatically for the minutes page based on the _Actual_ used topics.
The topics list can/will change through the meeting so I don't see how it can be used to do any automatic generation.

I can add #addtopic and #pushtopic to the minutes (similar to #info) but that would list them in the sequence they are done not the actual proposed agenda sequence. 

Thus i'm back to having #listtopics have an argument (#listtopics info) or maybe do a separate command for it that records it in minutes with proper agenda items.

**Comment by gastaldi** [comment]
Sounds good. Thanks!

**Comment by maxandersen** [comment]
this was actually done eons ago so closing it ;)
